# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hi~ This is xp!
email: linepuls@gamil.com
description: > # this means to ignore newlines until "baseurl:"
  这是xp，一名自由的独立游戏开发者。
baseurl: "" # the subpath of your site, e.g. /blog
url: "lpuls.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  lpuls

# Build settings
markdown: kramdown
